name: service
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  mockito: ^5.4.4
  darq: ^2.0.0
  shared_preferences: ^2.3.3
  
  domain:
    path: ../domain

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
