// Mocks generated by Mockito 5.4.4 from annotations
// in application/test/app/modules/assets/widgets/tree_items_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:domain/domain.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:service/src/services/assets_service.dart' as _i3;
import 'package:service/src/services/locations_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIAssetsRepository_0 extends _i1.SmartFake
    implements _i2.IAssetsRepository {
  _FakeIAssetsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompany_1 extends _i1.SmartFake implements _i2.Company {
  _FakeCompany_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAssetsTree_2 extends _i1.SmartFake implements _i2.AssetsTree {
  _FakeAssetsTree_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeILocationsRepository_3 extends _i1.SmartFake
    implements _i2.ILocationsRepository {
  _FakeILocationsRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AssetsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssetsService extends _i1.Mock implements _i3.AssetsService {
  @override
  _i2.IAssetsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIAssetsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeIAssetsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.IAssetsRepository);

  @override
  set repository(_i2.IAssetsRepository? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Company get company => (super.noSuchMethod(
        Invocation.getter(#company),
        returnValue: _FakeCompany_1(
          this,
          Invocation.getter(#company),
        ),
        returnValueForMissingStub: _FakeCompany_1(
          this,
          Invocation.getter(#company),
        ),
      ) as _i2.Company);

  @override
  set company(_i2.Company? value) => super.noSuchMethod(
        Invocation.setter(
          #company,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.AssetFilter> get customFilters => (super.noSuchMethod(
        Invocation.getter(#customFilters),
        returnValue: <_i2.AssetFilter>[],
        returnValueForMissingStub: <_i2.AssetFilter>[],
      ) as List<_i2.AssetFilter>);

  @override
  _i4.Future<List<_i2.Asset>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Asset>>.value(<_i2.Asset>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Asset>>.value(<_i2.Asset>[]),
      ) as _i4.Future<List<_i2.Asset>>);

  @override
  _i2.AssetsTree buildAssetsTree(
    List<_i2.Asset>? assets,
    List<_i2.Location>? locations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildAssetsTree,
          [
            assets,
            locations,
          ],
        ),
        returnValue: _FakeAssetsTree_2(
          this,
          Invocation.method(
            #buildAssetsTree,
            [
              assets,
              locations,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeAssetsTree_2(
          this,
          Invocation.method(
            #buildAssetsTree,
            [
              assets,
              locations,
            ],
          ),
        ),
      ) as _i2.AssetsTree);
}

/// A class which mocks [LocationsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationsService extends _i1.Mock implements _i5.LocationsService {
  @override
  _i2.ILocationsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeILocationsRepository_3(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeILocationsRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ILocationsRepository);

  @override
  set repository(_i2.ILocationsRepository? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Company get company => (super.noSuchMethod(
        Invocation.getter(#company),
        returnValue: _FakeCompany_1(
          this,
          Invocation.getter(#company),
        ),
        returnValueForMissingStub: _FakeCompany_1(
          this,
          Invocation.getter(#company),
        ),
      ) as _i2.Company);

  @override
  set company(_i2.Company? value) => super.noSuchMethod(
        Invocation.setter(
          #company,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i2.Location>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Location>>.value(<_i2.Location>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Location>>.value(<_i2.Location>[]),
      ) as _i4.Future<List<_i2.Location>>);
}
